import {useEffect,useState} from 'react';
import type {PublicPlayer} from '@saloon/protocol';
import {Icon} from './common';
import {voice} from '../voice';
export interface GamePreferences {effects:number;music:number;musicOn:boolean;voice:number;input:string;output:string;lowQuality:boolean;muted:boolean}
export const defaultPreferences:GamePreferences={effects:.7,music:.22,musicOn:true,voice:.8,input:'',output:'',lowQuality:false,muted:false};
export function readPreferences():GamePreferences{try{const p=JSON.parse(localStorage.getItem('saloon.settings')||'{}');const clamp=(v:unknown,d:number)=>typeof v==='number'&&Number.isFinite(v)?Math.max(0,Math.min(1,v)):d;return {...defaultPreferences,effects:clamp(p.effects,.7),music:clamp(p.music,.22),voice:clamp(p.voice,.8),musicOn:p.musicOn!==false,muted:p.muted===true,lowQuality:p.lowQuality===true,input:typeof p.input==='string'?p.input:'',output:typeof p.output==='string'?p.output:''};}catch{return defaultPreferences;}}
export function SettingsDrawer({prefs,setPrefs,micOn,toggleMic,players,selfId,mutedPlayers,setMutedPlayers,onClose}:{prefs:GamePreferences;setPrefs:(p:GamePreferences)=>void;micOn:boolean;toggleMic:()=>void;players:PublicPlayer[];selfId:string;mutedPlayers:string[];setMutedPlayers:(p:string[])=>void;onClose:()=>void}){
 const [tab,setTab]=useState<'sound'|'devices'|'players'>('sound'),[devices,setDevices]=useState<MediaDeviceInfo[]>([]),[error,setError]=useState('');
 const patch=(p:Partial<GamePreferences>)=>setPrefs({...prefs,...p});
 useEffect(()=>{const refresh=()=>{void navigator.mediaDevices?.enumerateDevices().then(setDevices).catch(()=>setError('Không đọc được thiết bị âm thanh.'));};refresh();navigator.mediaDevices?.addEventListener('devicechange',refresh);return()=>navigator.mediaDevices?.removeEventListener('devicechange',refresh);},[micOn]);
 const permission=async()=>{try{const stream=await navigator.mediaDevices.getUserMedia({audio:true,video:false});stream.getTracks().forEach(t=>t.stop());setDevices(await navigator.mediaDevices.enumerateDevices());setError('');}catch{setError('Chưa được cấp quyền mic. Hãy cấp quyền trong trình duyệt.');}};
 const outputSupported='setSinkId' in HTMLMediaElement.prototype||'setSinkId' in AudioContext.prototype;
 const slider=(label:string,key:'effects'|'music'|'voice')=><label className="settings-slider"><span>{label}<b>{Math.round(prefs[key]*100)}%</b></span><input type="range" aria-label={label} min={0} max={1} step={.01} value={prefs[key]} onChange={e=>patch({[key]:Number(e.target.value)})}/></label>;
 return <div className="drawer gx-drawer settings-drawer" role="dialog" aria-label="Cài đặt"><div className="drawer-heading"><div><span className="eyebrow">DEAD MAN’S DRAW</span><h2>Cài đặt</h2></div><button onClick={onClose} aria-label="Đóng cài đặt"><Icon name="close"/></button></div><div className="settings-tabs" role="tablist">{(['sound','devices','players'] as const).map((t,i)=><button key={t} role="tab" aria-selected={tab===t} onClick={()=>setTab(t)}>{['Âm thanh','Thiết bị','Người chơi'][i]}</button>)}</div>
 <div className="settings-content" role="tabpanel">
 {tab==='sound'&&<><label className="check-row"><input type="checkbox" checked={!prefs.muted} onChange={e=>patch({muted:!e.target.checked})}/> Bật hiệu ứng game</label>{slider('Âm lượng hiệu ứng','effects')}<label className="check-row"><input type="checkbox" checked={prefs.musicOn} onChange={e=>patch({musicOn:e.target.checked})}/> Bật nhạc nền</label>{slider('Âm lượng nhạc nền','music')}{slider('Âm lượng người chơi','voice')}<label className="check-row"><input type="checkbox" checked={prefs.lowQuality} onChange={e=>patch({lowQuality:e.target.checked})}/> Đồ họa nhẹ</label><p className="settings-note">Nhạc, hiệu ứng và giọng nói có âm lượng riêng. Lựa chọn được lưu trên máy này.</p></>}
 {tab==='devices'&&<><button className={`btn ${micOn?'outline':'gold'}`} onClick={toggleMic}>{micOn?'TẮT MIC':'BẬT MIC'}</button><label className="field-label">MIC ĐẦU VÀO</label><select aria-label="Mic đầu vào" value={prefs.input} onChange={e=>patch({input:e.target.value})}><option value="">Micro mặc định hệ thống</option>{devices.filter(d=>d.kind==='audioinput'&&d.deviceId!=='default').map((d,i)=><option key={d.deviceId||i} value={d.deviceId}>{d.label||`Micro ${i+1}`}</option>)}</select><label className="field-label">LOA ĐẦU RA</label><select aria-label="Loa đầu ra" disabled={!outputSupported} value={prefs.output} onChange={e=>patch({output:e.target.value})}><option value="">Loa mặc định hệ thống</option>{devices.filter(d=>d.kind==='audiooutput'&&d.deviceId!=='default').map((d,i)=><option key={d.deviceId||i} value={d.deviceId}>{d.label||`Loa ${i+1}`}</option>)}</select><button className="text-button" onClick={()=>void permission()}>Cấp quyền để hiện tên thiết bị</button><p className="settings-note">Mic chỉ mở khi bạn bấm bật. {outputSupported?'Loa được áp dụng cho nhạc, hiệu ứng và giọng nói.':'Trình duyệt này dùng loa do hệ điều hành chọn.'}</p></>}
 {tab==='players'&&<>{players.filter(p=>p.id!==selfId).map(p=><label key={p.id} className="check-row settings-player"><span>{p.name}{p.bot?' · máy':''}</span><input type="checkbox" disabled={p.bot} checked={mutedPlayers.includes(p.id)} onChange={e=>{voice.mutePlayer(p.id,e.target.checked);setMutedPlayers(e.target.checked?[...mutedPlayers,p.id]:mutedPlayers.filter(id=>id!==p.id));}}/> Tắt tiếng</label>)}{!players.length&&<p>Vào bàn để điều chỉnh giọng nói từng người.</p>}<p className="settings-note">Chỉ tắt tiếng ở phía bạn; những người khác vẫn nghe người đó.</p></>}
 {error&&<p role="alert">{error}</p>}
 </div></div>;
}
