import {useEffect,useId,useRef,useState} from 'react';
import type {RoomSnapshot} from '@saloon/protocol';
import {Icon} from './common';
import {PlayersList} from './Players';
import {RoomSetup} from './RoomSetup';
import {useDialog} from './useDialog';
import {connection,type CommandInput} from '../network';
export interface GamePreferences {effects:number;music:number;musicOn:boolean;voice:number;input:string;output:string;lowQuality:boolean;muted:boolean}
export const defaultPreferences:GamePreferences={effects:.7,music:.22,musicOn:true,voice:.8,input:'',output:'',lowQuality:false,muted:false};
export function readPreferences():GamePreferences{try{const p=JSON.parse(localStorage.getItem('saloon.settings')||'{}');const clamp=(v:unknown,d:number)=>typeof v==='number'&&Number.isFinite(v)?Math.max(0,Math.min(1,v)):d;return {...defaultPreferences,effects:clamp(p.effects,.7),music:clamp(p.music,.22),voice:clamp(p.voice,.8),musicOn:p.musicOn!==false,muted:p.muted===true,lowQuality:p.lowQuality===true,input:typeof p.input==='string'?p.input:'',output:typeof p.output==='string'?p.output:''};}catch{return defaultPreferences;}}
type SettingsTab='sound'|'devices'|'players'|'room';
export function SettingsDrawer({prefs,setPrefs,micOn,toggleMic,snapshot,selfId,send,mutedPlayers,onMute,onClose}:{prefs:GamePreferences;setPrefs:(p:GamePreferences)=>void;micOn:boolean;toggleMic:()=>void;snapshot:RoomSnapshot|null;selfId:string;send:(c:CommandInput)=>void;mutedPlayers:string[];onMute:(id:string,muted:boolean)=>void;onClose:()=>void}){
 const [tab,setTab]=useState<SettingsTab>('sound'),[devices,setDevices]=useState<MediaDeviceInfo[]>([]),[error,setError]=useState('');
 const root=useRef<HTMLDivElement>(null);useDialog(root,onClose);const id=useId();
 const host=!!snapshot&&snapshot.hostId===selfId;
 const patch=(p:Partial<GamePreferences>)=>setPrefs({...prefs,...p});
 useEffect(()=>{const refresh=()=>{void navigator.mediaDevices?.enumerateDevices().then(setDevices).catch(()=>setError('Không đọc được thiết bị âm thanh.'));};refresh();navigator.mediaDevices?.addEventListener('devicechange',refresh);return()=>navigator.mediaDevices?.removeEventListener('devicechange',refresh);},[micOn]);
 const permission=async()=>{try{const stream=await navigator.mediaDevices.getUserMedia({audio:true,video:false});stream.getTracks().forEach(t=>t.stop());setDevices(await navigator.mediaDevices.enumerateDevices());setError('');}catch{setError('Hãy cấp quyền mic trong trình duyệt rồi thử lại.');}};
 const outputSupported='setSinkId' in HTMLMediaElement.prototype||'setSinkId' in AudioContext.prototype;
 const slider=(label:string,key:'effects'|'music'|'voice')=><label className="settings-slider"><span>{label}<b>{Math.round(prefs[key]*100)}%</b></span><input type="range" aria-label={label} min={0} max={1} step={.01} value={prefs[key]} onChange={e=>patch({[key]:Number(e.target.value)})}/></label>;
 const tabs:[SettingsTab,string][]=[['sound','Âm thanh'],['devices','Thiết bị'],['players','Người chơi'],['room','Phòng']];
 return <><button type="button" className="surface-backdrop" onClick={onClose} aria-label="Đóng nền cài đặt" tabIndex={-1}/><div ref={root} className="drawer gx-drawer settings-drawer" role="dialog" aria-modal="true" aria-label="Cài đặt" tabIndex={-1}>
 <header className="surface-heading drawer-heading"><h2>Cài đặt</h2><button type="button" onClick={onClose} aria-label="Đóng cài đặt"><Icon name="close"/></button></header>
 <div className="settings-tabs" role="tablist" aria-label="Nhóm cài đặt">{tabs.map(([t,label],i)=><button key={t} id={`${id}-${t}`} role="tab" tabIndex={tab===t?0:-1} aria-selected={tab===t} aria-controls={`${id}-panel`} onClick={()=>setTab(t)} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowLeft'?-1:1)+tabs.length)%tabs.length;setTab(tabs[next][0]);document.getElementById(`${id}-${tabs[next][0]}`)?.focus();}}}>{label}</button>)}</div>
 <div className="settings-content" id={`${id}-panel`} role="tabpanel" aria-labelledby={`${id}-${tab}`}>
 {tab==='sound'&&<><label className="check-row"><span>Hiệu ứng game</span><input type="checkbox" checked={!prefs.muted} onChange={e=>patch({muted:!e.target.checked})}/></label>{slider('Âm lượng hiệu ứng','effects')}<label className="check-row"><span>Nhạc nền</span><input type="checkbox" checked={prefs.musicOn} onChange={e=>patch({musicOn:e.target.checked})}/></label>{slider('Âm lượng nhạc','music')}{slider('Giọng nói người chơi','voice')}<label className="check-row"><span>Đồ họa nhẹ</span><input type="checkbox" checked={prefs.lowQuality} onChange={e=>patch({lowQuality:e.target.checked})}/></label></>}
 {tab==='devices'&&<><button className={`btn ${micOn?'outline':'gold'}`} onClick={toggleMic}><Icon name={micOn?'micOff':'mic'}/>{micOn?'Tắt mic':'Bật mic'}</button><label className="device-field">Micro<select aria-label="Mic đầu vào" value={prefs.input} onChange={e=>patch({input:e.target.value})}><option value="">Mặc định hệ thống</option>{devices.filter(d=>d.kind==='audioinput'&&d.deviceId!=='default').map((d,i)=><option key={d.deviceId||i} value={d.deviceId}>{d.label||`Micro ${i+1}`}</option>)}</select></label><label className="device-field">Loa<select aria-label="Loa đầu ra" disabled={!outputSupported} value={prefs.output} onChange={e=>patch({output:e.target.value})}><option value="">Mặc định hệ thống</option>{devices.filter(d=>d.kind==='audiooutput'&&d.deviceId!=='default').map((d,i)=><option key={d.deviceId||i} value={d.deviceId}>{d.label||`Loa ${i+1}`}</option>)}</select></label><button className="btn outline" onClick={()=>void permission()}>Cấp quyền thiết bị</button>{!outputSupported&&<p className="settings-note">Chọn loa trong cài đặt hệ điều hành.</p>}</>}
 {tab==='players'&&(snapshot?<PlayersList snapshot={snapshot} selfId={selfId} send={send} mutedPlayers={mutedPlayers} onMute={onMute}/>:<p>Vào phòng để xem người chơi.</p>)}
 {tab==='room'&&(snapshot?<><div className="room-settings-info"><span>Mã phòng</span><strong>{snapshot.code}</strong></div>{snapshot.phase==='lobby'&&<RoomSetup snapshot={snapshot} host={host} send={send}/>}{host&&!['lobby','finished'].includes(snapshot.phase)&&<div className="room-danger-zone"><h3>Quản lý trận</h3><button type="button" className="btn outline danger" onClick={()=>{if(confirm('Kết thúc trận đang chơi sớm?')){send({type:'endMatch'});onClose();}}}>Kết thúc trận</button></div>}<button type="button" className="btn outline" onClick={()=>{if(confirm('Rời bàn chơi này?')){connection.leave();onClose();}}}><Icon name="exit"/>Rời bàn</button></>:<p>Vào phòng để xem cài đặt trận.</p>)}
 {error&&<p role="alert">{error}</p>}
 </div></div></>;
}
